// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rwgnldyndqvcgdqvvanp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3Z25sZHluZHF2Y2dkcXZ2YW5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NjAwMTIsImV4cCI6MjA2NjQzNjAxMn0.iEZgiJGE__GKM35jblWjXD7mgNQdI3TpZdhSwRLqIOI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);